baseURL = "https://huilla.net/"
title = "ğŸ¡ Leo Huilla"

[params]
   description = "Hello, I am Leo Huilla. Welcome to my webpage!"
   #copyright = "Copyright Â© 2020 Your Name"
   dark = "off"
   highlight = true
   enableEmoji = true

[permalinks]
    post = "/:title/"

[menu]

  [[menu.main]]
    name = "ğŸ“Writings"
    url = "/writings"
    weight = 10

  [[menu.main]]
    name = "ğŸ’»Stuff I Use"
    url = "/uses"
    weight = 20

  [[menu.main]]
    name = "ğŸ”—Links"
    url = "/links"
    weight = 30

  [[menu.main]]
    name = "ğŸ’¸Donate"
    url = "/donate"
    weight = 50

  [[menu.main]]
    name = "ğŸš§Projects"
    url = "/projects"
    weight = 40

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

